### ISSUE TITLE
HSC label from SMPL-X to SMPL

### ISSUE THREAD

**Issue by yyvhang** [paulchhuang/rich_toolkit#2]
Can you provide the vertex-to-vertex matrix or the code for converting the contact labeling from SMPLX to SMPL as mentioned in the article?

**Comment by paulchhuang** [comment]
Hi, 
Unfortunately RICH repo. doesn't have right to redistribute the data or the code you mentioned above. Please check this [repo](https://github.com/vchoutas/smplx/tree/main/transfer_model#smpl-x-to-smpl), and you can find the needed data in `smplx2smpl_deftrafo_setup.pkl` in `transfer_data` [here](https://github.com/vchoutas/smplx/tree/main/transfer_model#data). 

But actually RICH already provides HSC labels in _both_ format. Users don't need to bother converting between them:
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/10480537/236469738-a9ad27c1-4388-4abf-a9e9-7d94bd162c9a.png">
* SMPL-X: You can leverage the obj file, where vertices in contact are colored in green.
* SMPL: The corresponding pkl file has the per-vertex contact labels stored in the `contact` field. 

Hope that these are enough for your applications.
