### ISSUE TITLE
The downloading link of validation set may be something wrong.

### ISSUE THREAD

**Issue by leoisufa** [paulchhuang/rich_toolkit#3]
Hi, I try to obtain the JPG format of validation set in RICH. However, only can I download is an empty compressed file. The link is there [https://download.is.tue.mpg.de/download.php?domain=rich&resume=1&sfile=JPG_images/val.tar.gz](url)

**Comment by paulchhuang** [comment]
We just made a quick fix. Can you try again?

**Comment by leoisufa** [comment]
Thx, it can work well now.
