### ISSUE TITLE
about cam intrinsic and pose

### ISSUE THREAD

**Issue by rabbitchenrui** [paulchhuang/rich_toolkit#7]
Hi thans for your amazing dataset!

I have a question regarding the training data. We can observe that there are image information under the cam_10 label. However, in the intrinsic and extrinsic parameters provided by the rich_toolkit, we could not find the cam_10 identifier. Is it that this set of data has not been provided?

**Comment by rabbitchenrui** [comment]
@paulchhuang

**Comment by paulchhuang** [comment]
Hi @rabbitchenrui, 
We didn't calibrate the moving camera (cam_10) so there's no intrinsic nor extrinsic parameters for it.
